spring:
  datasource:
    url: jdbc:h2:mem:tt
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console.enabled: true
  data:
    web:
      pageable:
        page-parameter: pagina
        size-parameter: tamanho
      sort:
        sort-parameter: ordem


server:
  port : 8181
  error:
    include-message: always

api:
  security:
    token:
      secret: ${JWT_SECRET:123}